---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: dev-wordpress-acme-crt
spec:
  secretName: dev-wowimpression-acme-crt-secret
  dnsNames:
  - dev.wowimpression.cloud 
 
  issuerRef:
    name: letsencrypt-prod-wowimpression
  
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer
    group: cert-manager.io